spring.application.name=NavaBudSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/clients
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


telegram.bot.username=TestbotForSpring12345bot
telegram.bot.token=7636589004:AAFS3sC4Md22QmyA7UgHNWvrvQqHCRM4NeE



