spring.application.name=NavaBudSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/clients
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
